/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef STATICSHAPE
#define STATICSHAPE

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooAbsReal.h"
#include "RooHistPdf.h"
#include "RooDataHist.h"
 
class StaticShape : public RooAbsPdf {
public:
  StaticShape() : x_(), nx_(0), ny_(0), xvals_(0), yvals_(0) {}
  StaticShape(const char *name, const char *title, RooAbsReal& _x, double* _xvals, double* _yvals, unsigned _n);
  StaticShape(const char *name, const char *title, RooAbsReal& _x, double _xmin, double _xmax, double* _yvals, unsigned _n);
  StaticShape(const StaticShape& other, const char* name=0);
  virtual TObject* clone(const char* newname) const { return new StaticShape(*this,newname); }
  virtual ~StaticShape();

  RooHistPdf* toHistPdf(char const* = 0, RooDataHist** = 0) const;
  // Export this shape to RooHistPdf.
  // The RooDataHist used as the source of RooHistPdf will be returned in the second argument and must be deleted by the user.


protected:

  RooRealProxy x_;
  unsigned nx_;
  unsigned ny_;
  double* xvals_; //[nx_]
  double* yvals_; //[ny_]
  
  Double_t evaluate() const;

private:

  ClassDef(StaticShape,1) // Generic background shape with a lookup table
};
 
#endif
