#! /usr/bin/env python

from ROOT import *
from colors import *
colors = defineColors()

lumi = 1.0

######################################################

dataDir = "/afs/cern.ch/work/d/dabercro/public/Winter15/FilterTest/"
dataDir_eos = dataDir

physics_processes = {
        'Zll_ht100': { 'label':'Z#rightarrow ll',
                       'datacard':'Zll',
                       'color' : colors.keys()[0],
                       'ordering': 0,                  
                       'xsec' : 148.0,
                       'files':[dataDir+"monojet_DYJetsToLL_M-50_HT-100to200.root"],
                 },
        'Zll_ht200': { 'label':'Z#rightarrow ll',
                       'datacard':'Zll',
                       'color' : colors.keys()[0],
                       'ordering': 0,                  
                       'xsec' : 40.94,
                       'files':[dataDir+"monojet_DYJetsToLL_M-50_HT-200to400.root"],
                       },
        'Zll_ht400': { 'label':'Z#rightarrow ll',
                       'datacard':'Zll',
                       'color' : colors.keys()[0],
                       'ordering': 0,                  
                       'xsec' : 5.497,
                       'files':[dataDir+"monojet_DYJetsToLL_M-50_HT-400to600.root"],
                 },
        'Zll_ht600': { 'label':'Z#rightarrow ll',
                       'datacard':'Zll',
                       'color' : colors.keys()[0],
                       'ordering': 0,                  
                       'xsec' : 2.193,
                       'files':[dataDir+"monojet_DYJetsToLL_M-50_HT-600toInf.root"],
                 },        

        'Zvv_ht100':{ 'label':'Z#rightarrow#nu#nu', 
                      'datacard':'Zvv', 
                      'color' : colors.keys()[4], 
                      'ordering': 4,
                      'xsec' : 280.5,
                      'files':[dataDir+"monojet_ZJetsToNuNu_HT-100To200_13TeV.root"],
                      },
        'Zvv_ht200':{ 'label':'Z#rightarrow#nu#nu', 
                      'datacard':'Zvv', 
                      'color' : colors.keys()[4], 
                      'ordering': 4,
                      'xsec' : 78.36,
                      'files':[dataDir+"monojet_ZJetsToNuNu_HT-200To400_13TeV.root"],
                      },
        'Zvv_ht400':{ 'label':'Z#rightarrow#nu#nu', 
                      'datacard':'Zvv', 
                      'color' : colors.keys()[4], 
                      'ordering': 4,
                      'xsec' : 10.94,
                      'files':[dataDir+"monojet_ZJetsToNuNu_HT-400To600_13TeV.root"],
                      },
        'Zvv_ht600':{ 'label':'Z#rightarrow#nu#nu', 
                      'datacard':'Zvv', 
                      'color' : colors.keys()[4], 
                      'ordering': 4,
                      'xsec' : 4.20,
                      'files':[dataDir+"monojet_ZJetsToNuNu_HT-600ToInf_13TeV.root"],
                      },


        'Wlv_ht100': { 'label':'W#rightarrow  l#nu',
                       'datacard':'Wlv',
                       'color' : colors.keys()[2],
                       'ordering': 3,                  
                       'xsec' : 1343.,
                       'files':[dataDir+"monojet_WJetsToLNu_HT-100To200.root"],
                       },
        'Wlv_ht200': { 'label':'W#rightarrow  l#nu',
                       'datacard':'Wlv',
                       'color' : colors.keys()[2],
                       'ordering': 3,                  
                       'xsec' : 359.6,
                       'files':[dataDir+"monojet_WJetsToLNu_HT-200To400.root"],
                       },
        'Wlv_ht400': { 'label':'W#rightarrow  l#nu',
                       'datacard':'Wlv',
                       'color' : colors.keys()[2],
                       'ordering': 3,                  
                       'xsec' : 48.85,
                       'files':[dataDir+"monojet_WJetsToLNu_HT-400To600.root"],
                       },
        'Wlv_ht600': { 'label':'W#rightarrow  l#nu',
                       'datacard':'Wlv',
                       'color' : colors.keys()[2],
                       'ordering': 3,                  
                       'xsec' : 18.91,
                       'files':[dataDir+"monojet_WJetsToLNu_HT-600ToInf.root"],
                       },

        'QCD_200To300': { 'label':'QCD',
                          'datacard':'qcd',
                          'color' : colors.keys()[1],
                          'ordering': 1,
                          'xsec' : 1735000.0,
                          'files':[dataDir+"monojet_QCD_HT200to300.root"],
                          },
        'QCD_300To500': { 'label':'QCD',
                          'datacard':'qcd',
                          'color' : colors.keys()[1],
                          'ordering': 1,
                          'xsec' : 366800.0,
                          'files':[dataDir+"monojet_QCD_HT300to500.root"],
                          },
        'QCD_500To700': { 'label':'QCD',
                          'datacard':'qcd',
                          'color' : colors.keys()[1],
                          'ordering': 1,
                          'xsec' : 29370.0,
                          'files':[dataDir+"monojet_QCD_HT500to700.root"],
                          },
        'QCD_700To1000': { 'label':'QCD',
                           'datacard':'qcd',
                           'color' : colors.keys()[1],
                           'ordering': 1,
                           'xsec' : 6524.0,
                           'files':[dataDir+"monojet_QCD_HT700to1000.root"],
                           },
        'QCD_1000To1500': { 'label':'QCD',
                            'datacard':'qcd',
                            'color' : colors.keys()[1],
                            'ordering': 1,
                            'xsec' : 1064.0,
                            'files':[dataDir+"monojet_QCD_HT1000to1500.root"],
                            },

        'GJets_40To100': { 'label':'#gamma + jets',
                           'datacard': 'gjets',
                           'color' :  colors.keys()[6],
                           'ordering': 2,
                           'xsec' : 23080.0,
                           'files':[dataDir+"monojet_GJets_HT-40To100.root"],
                           },
        'GJets_100To200': { 'label':'#gamma + jets',
                            'datacard': 'gjets',
                            'color' :  colors.keys()[6],
                            'ordering': 2,
                            'xsec' : 9235.0,
                            'files':[dataDir+"monojet_GJets_HT-100To200.root"],
                            },
        'GJets_200To400': { 'label':'#gamma + jets',
                            'datacard': 'gjets',
                            'color' :  colors.keys()[6],
                            'ordering': 2,
                            'xsec' : 2298.0,
                            'files':[dataDir+"monojet_GJets_HT-200To400.root"],
                           },
        'GJets_400To600': { 'label':'#gamma + jets',
                            'datacard': 'gjets',
                            'color' :  colors.keys()[6],
                            'ordering': 2,
                            'xsec' : 277.6,
                            'files':[dataDir+"monojet_GJets_HT-400To600.root"],
                            },
        'GJets_600ToInf': { 'label':'#gamma + jets',
                            'datacard': 'gjets',
                            'color' :  colors.keys()[6],
                            'ordering': 2,
                            'xsec' : 93.47,
                            'files':[dataDir+"monojet_GJets_HT-600ToInf.root"],
                            },
        'others': { #'label':'Top quark + diboson',
                'label':'top',
                    'datacard':'others',
                    'color' : colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 831.76,
                    'files':[dataDir+"monojet_TTJets.root"],
                    },        
        'antitop': { #'label':'Top quark + diboson',
                'label':'top',
                    'datacard':'others',
                    'color' : colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 26.22,
                    'files':[dataDir_eos+"monojet_ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8.root"],
                    },
        'top': { #'label':'Top quark + diboson',
                'label':'top',
                    'datacard':'others',
                    'color' : colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 44.07,
                    'files':[dataDir_eos+"monojet_ST_t-channel_top_4f_leptonDecays_13TeV-powheg-pythia8.root"],
                    },
        'antitop_5f': { #'label':'Top quark + diboson',
                'label':'top',
                    'datacard':'others',
                    'color' : colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 35.6,
                    'files':[dataDir_eos+"monojet_ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8.root"],
                    },
        'top_5f': { #'label':'Top quark + diboson',
                'label':'top',
                    'datacard':'others',
                    'color' : colors.keys()[3],
                    'ordering': 2,
                    'xsec' : 35.6,
                    'files':[dataDir_eos+"monojet_ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8.root"],
                    },
        'WW' : { #'label':'Top quark + diboson',
                'label':'VV',
                 'datacard':'others',
                 'color':colors.keys()[5],
                 'ordering': 2,
                 'xsec' : 118.7, #63.21,
                 'files':[dataDir_eos+"monojet_WW.root"],
                 },
        'ZZ' : { #'label':'Top quark + diboson',
                'label':'VV',
                 'datacard':'others',
                 'color':colors.keys()[5],
                 'ordering': 2,
                 'xsec' : 16.6, #10.32,
                 'files':[dataDir_eos+"monojet_ZZ.root"],
                 },
        'WZ' : { #'label':'Top quark + diboson',
                'label':'VV',
                 'datacard':'others',
                 'color':colors.keys()[5],
                 'ordering': 2,
                 'xsec' : 47.2, #22.82,
                 'files':[dataDir_eos+"monojet_WZ.root"],
                 },
        
        #991.600 fb--> 0.991 * 10 pb  
        'signal_dm': { 'label':'AV (2 TeV)',
                          'datacard':'signal',
                          'color' : 1,
                          'ordering': 5,
                          'xsec' : 1.,
                           'files':[dataDir+"monojet_DMV_NNPDF30_Axial_Mphi-2000_Mchi-1_gSM-1p0_gDM-1p0_13TeV-powheg+RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1+AODSIM.root"],
                          },
        'signal_dm_av_1_2': { 'label':'V (1 TeV)',
                          'datacard':'signal',
                          'color' : 1,
                          'ordering': 5,
                          'xsec' : 1.,
                           'files':[dataDir+"monojet_DMV_NNPDF30_Axial_Mphi-2000_Mchi-1_gSM-1p0_gDM-1p0_13TeV-powheg+RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1+AODSIM.root"],
                              },

        'data': { 'label':'Data',
                  'datacard':'data',
                  'color': 1,
                  'ordering': 6,    
                  'xsec' : 1.0,                  
                  'files':[dataDir+"monojet_MET.root"],
                  }
        }

tmp = {}
for p in physics_processes: 
	if physics_processes[p]['ordering']>-1: tmp[p] = physics_processes[p]['ordering']
ordered_physics_processes = []

for key, value in sorted(tmp.iteritems(), key=lambda (k,v): (v,k)):
	ordered_physics_processes.append(key)

def makeTrees(process,tree,channel):
	Trees={}
	Trees[process] = TChain(tree)
	for sample in  physics_processes[process]['files']:
		Trees[process].Add(sample)
	return Trees[process]

######################################################
